# Generated by Django 5.2.7 on 2025-10-21 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=20)),
                ('price', models.IntegerField(max_length=7)),
                ('contact', models.TextField(max_length=500)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
    ]
