# Generated by Django 5.2.7 on 2025-10-27 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page1', '0002_sign_alter_products_options_alter_products_contact_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'ordering': ['name'], 'verbose_name': 'car market'},
        ),
        migrations.AlterField(
            model_name='products',
            name='type',
            field=models.CharField(choices=[('hypird', 'hypird'), ('city', 'city'), ('offroad', 'offroad')], max_length=20),
        ),
        migrations.AlterField(
            model_name='sign',
            name='password',
            field=models.CharField(max_length=25),
        ),
    ]
